### ISSUE TITLE
"Qwen/Qwen1.5-72B-Chat" does not support parameter n and returns multiple results at the same time, even if I set the parameter temperature

### ISSUE THREAD

**Issue by andy2332** [togethercomputer/together-python#128]
**Describe the bug**
"Qwen/Qwen1.5-72B-Chat" does not support parameter n and returns multiple results at the same time, even if I set the parameter temperature

**To Reproduce**
'''
import os
from together import Together

client = Together(api_key=os.environ.get("TOGETHER_API_KEY"))

response = client.chat.completions.create(
    model="Qwen/Qwen1.5-72B-Chat",
    messages=[{"role": "user", "content": "tell me about new york"}],
    temperature=0.9,
    n=3
)
print(response)
print(response.choices[0].message.content)
'''
**Expected behavior**
Return multiple results at the same time

**Comment by orangetin** [comment]
this doesn't seem like an issue with the Python SDK, but rather with the API. Please open a ticket with support: https://www.together.ai/contact
