### ISSUE TITLE
Llama-3 models hallucinate when `stop` is not found in output.

### ISSUE THREAD

**Issue by Infrared1029** [togethercomputer/together-python#137]
```python
import os
from together import Together

client = Together(api_key="my_key")

response = client.chat.completions.create(
    model="meta-llama/Llama-3-70b-chat-hf",
    messages=[{"role": "user", "content": "write `bar` then `foo` three times"}],
    max_tokens=200,
    stop=["test"]
)
print(response.choices[0].message.content)
```

outputs:
```
Here is the output:

bar
foo
foo
fooassistant

Here is the output:

bar
foo
foo
fooassistant

Here is the output:
...
```

seems to happen with llama 3 models only? llama 2 does fine.

**Comment by Infrared1029** [comment]
> <|eot_id|>

![image](https://github.com/togethercomputer/together-python/assets/60873139/4fcc61b7-c5a7-400b-9605-610770878ee8)

yeah works.

**Comment by Infrared1029** [comment]
> can you also try passing in `<|eot_id|>` in the list of stop tokens? I believe what's happening is that the tokenizer is ignoring it.

yeah works
![image](https://github.com/togethercomputer/together-python/assets/60873139/fec83371-57f5-49c1-b996-359b5783bfb5)

**Comment by orangetin** [comment]
sweet! will patch this server side too.
