### ISSUE TITLE
meta-llama/Llama-Vision-Free is not supported for JSON mode/function calling

### ISSUE THREAD

**Issue by ankitvgupta** [togethercomputer/together-python#196]
**Describe the bug**
Getting the error message `meta-llama/Llama-Vision-Free is not supported for JSON mode/function calling` but this doesn't appear to be documented anywhere. Just wanted to confirm that this was the case or if its a bug.

**To Reproduce**
Try to use that APi call with a tools array.

**Expected behavior
A clear and concise description of what you expected to happen.**
I expected the function calling to work

**Comment by orangetin** [comment]
yes, that is right. Function Calling & JSON mode support coming soon!
